// src/hooks/solidjs/useStoreSelector.ts
import { createSignal, onCleanup, onMount } from 'solid-js';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStoreSelector = <T extends StateConstraint, U extends keyof T>(
	store: ReturnStoreType<T>,
	key: U
): (() => T[U]) => {
	const [state, setState] = createSignal(store.getState()[key]);
	let unsubscribe: () => void;

	onMount(() => {
		unsubscribe = store.subscribeKey(key, (v) => {
			setState(() => v);
		});
	});

	onCleanup(() => {
		unsubscribe();
	});

	return state;
};

// packages/react/src/useStoreSelector.ts
import { ReturnStoreType, StateConstraint } from '@poly-state/poly-state';
import { useEffect, useRef, useState } from 'react';

export const useStoreSelector = <T extends StateConstraint, U>(
	store: ReturnStoreType<T>,
	fn: (store: T) => U
) => {
	const subscriberRef = useRef<() => void>();
	const fnRef = useRef(fn);
	const [state, setState] = useState(() => fnRef.current(store.getState()));

	useEffect(() => {
		fnRef.current = fn;
	}, [fn]);

	useEffect(() => {
		//clean up previous listener if dependencies change
		subscriberRef.current?.();
		subscriberRef.current = store.subscribe((v) => setState(fnRef.current(v)));

		return () => subscriberRef.current?.();
	}, [store]);

	return state;
};

export const createStoreSelector = <T extends StateConstraint>(store: ReturnStoreType<T>) => {
	return <U>(fn: (store: T) => U) => useStoreSelector(store, fn);
};
