// src/hooks/react/useStore.ts
import { useEffect, useState } from 'react';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStore = <T extends StateConstraint>(store: ReturnStoreType<T>) => {
	const [state, setState] = useState(store.getState());
	useEffect(() => store.subscribe(setState), [store]);
	return state;
};

// src/hooks/solidjs/useStore.ts
import { createSignal, onCleanup, onMount } from 'solid-js';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStore = <T extends StateConstraint>(store: ReturnStoreType<T>) => {
	const [state, setState] = createSignal(store.getState());
	let unsubscribe: () => void;

	onMount(() => {
		unsubscribe = store.subscribe((v) => {
			setState(() => v);
		});
	});

	onCleanup(() => {
		unsubscribe();
	});

	return state;
};
