// packages/react/src/useStore.ts
import { ReturnStoreType, StateConstraint } from '@poly-state/poly-state';
import { useEffect, useState } from 'react';

export const useStore = <T extends StateConstraint>(store: ReturnStoreType<T>) => {
	const [state, setState] = useState(() => store.getState());

	useEffect(() => {
		const unsub = store.subscribe((v) => setState(v));
		return () => unsub();
	}, [store]);

	return state;
};

// src/hooks/solidjs/useStore.ts
import { createSignal, onCleanup, onMount } from 'solid-js';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStore = <T extends StateConstraint>(store: ReturnStoreType<T>) => {
	const [state, setState] = createSignal(store.getState());
	let unsubscribe: () => void;

	onMount(() => {
		unsubscribe = store.subscribe((v) => {
			setState(() => v);
		});
	});

	onCleanup(() => {
		unsubscribe();
	});

	return state;
};
