// src/hooks/react/useStoreSelector.ts
import { useEffect, useRef, useState } from 'react';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStoreSelector = <T extends StateConstraint, U extends keyof T>(
	store: ReturnStoreType<T>,
	key: U
): T[U] => {
	const [state, setState] = useState(store.getState()[key]);

	const subscriberRef = useRef<() => void>();

	useEffect(() => {
		//clean up previous listeners if dependencies change
		if (subscriberRef.current) {
			subscriberRef.current();
		}

		subscriberRef.current = store.subscribeKey(key, setState);

		return () => {
			if (subscriberRef?.current) {
				subscriberRef.current();
			}
		};
	}, [store, key]);

	return state;
};

// src/hooks/solidjs/useStoreSelector.ts
import { createSignal, onCleanup, onMount } from 'solid-js';
import { ReturnStoreType, StateConstraint } from '../../types';

export const useStoreSelector = <T extends StateConstraint, U extends keyof T>(
	store: ReturnStoreType<T>,
	key: U
): (() => T[U]) => {
	const [state, setState] = createSignal(store.getState()[key]);
	let unsubscribe: () => void;

	onMount(() => {
		unsubscribe = store.subscribeKey(key, (v) => {
			setState(() => v);
		});
	});

	onCleanup(() => {
		unsubscribe();
	});

	return state;
};
